lilypond:
	pandoc \
	--pdf-engine=lualatex \
	--pdf-engine-opt=--shell-escape \
	-V fontfamily=libertine \
	--toc-depth=4 \
	 -o lilypond.pdf lilypond.md

structure:
	pandoc \
	--pdf-engine=lualatex \
	--pdf-engine-opt=--shell-escape \
	-V fontfamily=libertine \
	--toc-depth=4 \
	 -o structure.pdf structure.md